#!/bin/sh
# xprofile - read by display managers at the beginning of the X user session

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
