zsh_source_file() {
    [ -f "$1" ] && source "$1"
    return 0 # avoid non-zero return codes when file does not exists
}

# source ZSH settings
zsh_source_file "${ZDOTDIR:-$HOME/.config/zsh}/settings.zsh"

# source ZSH key bindings
zsh_source_file "${ZDOTDIR:-$HOME/.config/zsh}/keybindings.zsh"

# source ZSH prompt
zsh_source_file "${ZDOTDIR:-$HOME/.config/zsh}/prompt.zsh"

# source ZSH plugin manager
zsh_source_file "${ZDOTDIR:-$HOME/.config/zsh}/plugins.zsh"

# source aliases
zsh_source_file "$HOME/.config/shell/aliasrc"

# source defaults
zsh_source_file "$HOME/.config/shell/defaults"

# source functions
zsh_source_file "$HOME/.config/shell/functions"

# source fzf functions
zsh_source_file "$HOME/.config/shell/fzfrc"

# add plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zdharma-continuum/fast-syntax-highlighting"

# local customizations
zsh_source_file "${ZDOTDIR:-$HOME/.config/zsh}/zshrc_local"
