zsh_source_file() {
    [ -f "$1" ] && source "$1"
}

# source ZSH settings
zsh_source_file "${ZDOTDIR:-$HOME/.config/zsh}/settings.zsh"

# source ZSH key bindings
zsh_source_file "${ZDOTDIR:-$HOME/.config/zsh}/keybindings.zsh"

# source ZSH prompt
zsh_source_file "${ZDOTDIR:-$HOME/.config/zsh}/prompt.zsh"

# source aliases
zsh_source_file "$HOME/.config/shell/aliasrc"

# source defaults
zsh_source_file "$HOME/.config/shell/defaults"

# source functions
zsh_source_file "$HOME/.config/shell/functions"

# source fzf functions
zsh_source_file "$HOME/.config/shell/fzfrc"

# local customizations
zsh_source_file "${ZDOTDIR:-$HOME/.config/zsh}/zshrc_local"
